services:
  app:
    container_name: userge-basic
    build:
      context: .
      dockerfile: Dockerfile.basic
    image: docker.io/onurmercury/userge-loader:basic
#    image: ghcr.io/onurmercury/userge-loader:basic
    restart: on-failure
    env_file:
      - config.env
