#!/bin/bash
set -e

commit="b6723d8a56a180290b687c458012879c49dd9c32"

# download the plugin repository
wget -q -O - https://github.com/UsergeTeam/Userge-Plugins/archive/"${commit}".tar.gz | tar xz

# find the python packages
find Userge-Plugins-"${commit}"/ -name config.ini -exec grep packages {} \; | \
sed 's/packages://g; /^$/d; s/ //; s/, /\n/g' | \
sort -uf > python-packages.txt

# exclude unavailable/broken packages from python-packages.txt
sed -i '

  # deezloader
  /TomyPrs\/deezloader/d

  # covid
  /covid/d

  # music
  /python-arq/d

  # video_chat
  /py-tgcalls/d; /youtube-search-python/d

  # webss
  /fake-headers/d; /^selenium$/d

  ' python-packages.txt

# install packages
pip install -Ur python-packages.txt --no-cache-dir

# remove temporary files
rm -rf Userge-Plugins-"${commit}"/ python-packages.txt
